[package]
name = "cardwire-daemon"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Daemon for cardwire GPU management"

[dependencies]
cardwire-policy = { path = "../cardwire-policy" }
cardwire-ebpf-userspace = { path = "../cardwire-ebpf-userspace" }
tokio.workspace = true
zbus.workspace = true
serde.workspace = true
log.workspace = true
thiserror.workspace = true
env_logger.workspace = true
toml.workspace = true
serde_json.workspace = true
tokio-stream.workspace = true
aya.workspace = true
xdg.workspace = true
freedesktop-desktop-entry.workspace = true
udev.workspace = true
aya-log.workspace = true
vulkano.workspace = true
khronos-egl.workspace = true
rusqlite.workspace = true
inotify.workspace = true

[[bin]]
name = "cardwired"
path = "src/daemon.rs"

[package.metadata.deb]
name = "cardwire"
maintainer = "luytan <luytan@khora.me>"
copyright = "2026, luytan"
section = "utils"
priority = "optional"
extended-description = """\
 GPU manager for Linux using eBPF LSM hooks."""
depends = "hwdata, dbus, systemd, upower, udev, libgcc-s1, libc6, libudev1"

assets = [
    ["target/release/cardwired", "usr/bin/", "755"],
    ["target/release/cardwire", "usr/bin/", "755"],
    ["target/release/cardwire-gui", "usr/bin/", "755"],
    ["../../assets/cardwired.service", "usr/lib/systemd/system/", "644"],
    ["../../assets/99-cardwired.preset", "usr/lib/systemd/system-preset/", "644"],
    ["../../assets/org.opengamingcollective.cardwire.conf", "usr/share/dbus-1/system.d/", "644"],
    ["../../assets/cardwire-gui.desktop", "usr/share/applications/", "644"],
    ["../../assets/org.opengamingcollective.cardwire.metainfo.xml", "usr/share/metainfo/", "644"],
    ["../../assets/icons/org.opengamingcollective.cardwire.tray.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
    ["../../assets/icons/org.opengamingcollective.cardwire.tray-integrated.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
    ["../../assets/icons/org.opengamingcollective.cardwire.tray-hybrid.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
    ["../../assets/icons/org.opengamingcollective.cardwire.tray-manual.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
    ["../../assets/icons/org.opengamingcollective.cardwire.tray-smart.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
]
maintainer-scripts = "../../packages/debian/DEBIAN"
changelog = "../../packages/debian/changelog"
